version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: isaiahsolo/trackhours-client
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: isaiahsolo/trackhours-server
